import type { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Microcontrollers",
    slug: "microcontrollers",
    description: "Development boards and microcontroller modules for every project",
    image: "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=600&q=80",
    subCategories: [
      { id: "sub-1", name: "Arduino", slug: "arduino", productCount: 45 },
      { id: "sub-2", name: "ESP32", slug: "esp32", productCount: 38 },
      { id: "sub-3", name: "STM32", slug: "stm32", productCount: 29 },
      { id: "sub-4", name: "Raspberry Pi", slug: "raspberry-pi", productCount: 22 },
      { id: "sub-5", name: "AVR", slug: "avr", productCount: 18 },
    ],
    productCount: 342,
  },
  {
    id: "cat-2",
    name: "Sensors & Modules",
    slug: "sensors",
    description: "Environmental, motion, distance and specialized sensors",
    image: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600&q=80",
    subCategories: [
      { id: "sub-6", name: "Temperature & Humidity", slug: "temperature-humidity", productCount: 52 },
      { id: "sub-7", name: "Motion & Distance", slug: "motion-distance", productCount: 44 },
      { id: "sub-8", name: "Gas & Air Quality", slug: "gas-air-quality", productCount: 28 },
      { id: "sub-9", name: "Pressure & Force", slug: "pressure-force", productCount: 22 },
    ],
    productCount: 523,
  },
  {
    id: "cat-3",
    name: "Motors & Drivers",
    slug: "motors",
    description: "Stepper motors, servo motors, DC motors and driver boards",
    image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&q=80",
    subCategories: [
      { id: "sub-10", name: "Stepper Motors", slug: "stepper-motors", productCount: 32 },
      { id: "sub-11", name: "Servo Motors", slug: "servo-motors", productCount: 28 },
      { id: "sub-12", name: "DC Motors", slug: "dc-motors", productCount: 24 },
      { id: "sub-13", name: "Motor Drivers", slug: "motor-drivers", productCount: 35 },
    ],
    productCount: 182,
  },
  {
    id: "cat-4",
    name: "Displays & OLEDs",
    slug: "displays",
    description: "LCD, OLED, TFT and e-paper display modules",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&q=80",
    subCategories: [
      { id: "sub-14", name: "OLED Displays", slug: "oled-displays", productCount: 28 },
      { id: "sub-15", name: "TFT LCD", slug: "tft-lcd", productCount: 22 },
      { id: "sub-16", name: "E-Paper", slug: "e-paper", productCount: 12 },
      { id: "sub-17", name: "7-Segment", slug: "7-segment", productCount: 18 },
    ],
    productCount: 124,
  },
  {
    id: "cat-5",
    name: "Power Management",
    slug: "power-management",
    description: "Voltage regulators, DC-DC converters and battery management",
    image: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600&q=80",
    subCategories: [
      { id: "sub-18", name: "Voltage Regulators", slug: "voltage-regulators", productCount: 45 },
      { id: "sub-19", name: "DC-DC Converters", slug: "dc-dc-converters", productCount: 38 },
      { id: "sub-20", name: "Battery Management", slug: "battery-management", productCount: 25 },
      { id: "sub-21", name: "Power Supplies", slug: "power-supplies", productCount: 30 },
    ],
    productCount: 284,
  },
  {
    id: "cat-6",
    name: "Connectors & Cables",
    slug: "connectors",
    description: "Headers, terminal blocks, wires, adapters and cabling",
    image: "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=600&q=80",
    subCategories: [
      { id: "sub-22", name: "Pin Headers", slug: "pin-headers", productCount: 55 },
      { id: "sub-23", name: "Terminal Blocks", slug: "terminal-blocks", productCount: 38 },
      { id: "sub-24", name: "USB Connectors", slug: "usb-connectors", productCount: 32 },
      { id: "sub-25", name: "Audio Connectors", slug: "audio-connectors", productCount: 28 },
    ],
    productCount: 453,
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "ESP32-WROOM-32 Development Board",
    slug: "esp32-wroom-32-development-board",
    description: "The ESP32-WROOM-32 is a powerful, generic Wi-Fi+BT+BLE MCU module that targets a wide variety of applications, ranging from low-power sensor networks to the most demanding tasks, such as voice encoding, music streaming and MP3 decoding.",
    shortDescription: "Dual-core 240MHz MCU with integrated Wi-Fi & Bluetooth",
    price: 14.99,
    originalPrice: 19.99,
    images: [
      "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=400&q=60",
      "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=400&q=60",
    ],
    category: "Microcontrollers",
    subCategory: "ESP32",
    brand: "Espressif",
    inStock: true,
    stockQuantity: 2450,
    rating: 4.8,
    reviewCount: 1247,
    specifications: {
      "Processor": "Xtensa dual-core 32-bit LX6",
      "Clock Speed": "240 MHz",
      "SRAM": "520 KB",
      "Flash": "4 MB",
      "Wi-Fi": "802.11 b/g/n",
      "Bluetooth": "BLE 4.2",
      "GPIO": "34",
      "Operating Voltage": "3.3V",
    },
    features: [
      "Dual-core Tensilica LX6 microprocessor",
      "Integrated 802.11 b/g/n Wi-Fi transceiver",
      "Bluetooth 4.2 and BLE support",
      "Ultra-low power consumption",
      "Rich peripheral set including SPI, I2C, UART, I2S",
      "On-board PCB antenna",
    ],
    tags: ["esp32", "wifi", "bluetooth", "iot", "microcontroller"],
    isNew: true,
    isFeatured: true,
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "prod-2",
    name: "Raspberry Pi 5 - 8GB",
    slug: "raspberry-pi-5-8gb",
    description: "The Raspberry Pi 5 is the latest flagship single-board computer, featuring a 2.4GHz quad-core 64-bit Arm Cortex-A76 processor, VideoCore VII GPU, and dual HDMI 4Kp60 output.",
    shortDescription: "Next-gen SBC with 2.4GHz quad-core processor",
    price: 79.99,
    images: [
      "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&q=60",
    ],
    category: "Microcontrollers",
    subCategory: "Raspberry Pi",
    brand: "Raspberry Pi Foundation",
    inStock: true,
    stockQuantity: 680,
    rating: 4.9,
    reviewCount: 892,
    specifications: {
      "Processor": "Broadcom BCM2712 quad-core Cortex-A76",
      "Clock Speed": "2.4 GHz",
      "RAM": "8 GB LPDDR4X",
      "GPU": "VideoCore VII",
      "USB": "2x USB 3.0, 2x USB 2.0",
      "Display": "Dual HDMI 4Kp60",
      "Networking": "Gigabit Ethernet, Wi-Fi 5, BLE 5.0",
      "GPIO": "40-pin header",
    },
    features: [
      "2.4GHz quad-core 64-bit Arm Cortex-A76 CPU",
      "VideoCore VII GPU supporting OpenGL ES 3.1, Vulkan 1.2",
      "Dual HDMI 4Kp60 display output",
      "PCIe 2.0 x1 interface",
      "USB 3.0 with simultaneous 5Gbps operation",
      "RTC and power management",
    ],
    tags: ["raspberry-pi", "sbc", "computer", "linux"],
    isFeatured: true,
    isOnSale: false,
    createdAt: "2025-10-15T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "prod-3",
    name: "DHT22 Digital Temperature & Humidity Sensor",
    slug: "dht22-temperature-humidity-sensor",
    description: "The DHT22 is a basic, low-cost digital temperature and humidity sensor. It uses a capacitive humidity sensor and a thermistor to measure the surrounding air, and outputs a digital signal on the data pin.",
    shortDescription: "High-precision digital temperature and humidity sensor",
    price: 4.99,
    images: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=60",
    ],
    category: "Sensors & Modules",
    subCategory: "Temperature & Humidity",
    brand: "Aosong",
    inStock: true,
    stockQuantity: 8200,
    rating: 4.5,
    reviewCount: 2103,
    specifications: {
      "Temperature Range": "-40°C to 80°C",
      "Temperature Accuracy": "±0.5°C",
      "Humidity Range": "0-100% RH",
      "Humidity Accuracy": "±2% RH",
      "Sampling Rate": "0.5 Hz",
      "Operating Voltage": "3.3V - 5.5V",
      "Interface": "Single-bus digital",
    },
    features: [
      "Digital single-bus interface",
      "Excellent long-term stability",
      "Low power consumption",
      "Comprehensive calibration",
      "20m cable length capability",
    ],
    tags: ["temperature", "humidity", "sensor", "dht22"],
    isFeatured: true,
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "prod-4",
    name: "Arduino Uno R4 WiFi",
    slug: "arduino-uno-r4-wifi",
    description: "The Arduino Uno R4 WiFi combines the classic UNO form factor with a powerful 32-bit RA4M1 processor and built-in Wi-Fi/Bluetooth module, making it perfect for IoT projects.",
    shortDescription: "Classic UNO with 32-bit power and wireless connectivity",
    price: 27.50,
    originalPrice: 34.99,
    images: [
      "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=400&q=60",
    ],
    category: "Microcontrollers",
    subCategory: "Arduino",
    brand: "Arduino",
    inStock: true,
    stockQuantity: 1200,
    rating: 4.7,
    reviewCount: 1567,
    specifications: {
      "Microcontroller": "RA4M1 (Arm Cortex-M4)",
      "Clock Speed": "48 MHz",
      "SRAM": "32 KB",
      "Flash": "256 KB",
      "Digital I/O": "14",
      "Analog Input": "6",
      "Wi-Fi": "ESP32-S3 module",
      "Bluetooth": "BLE 5.0",
    },
    features: [
      "32-bit Arm Cortex-M4 core",
      "Built-in ESP32-S3 for Wi-Fi and BLE",
      "12x8 LED matrix",
      "USB-C connector",
      "Qwiic / STEMMA connector",
      "HID keyboard/mouse support",
    ],
    tags: ["arduino", "uno", "wifi", "iot", "microcontroller"],
    isNew: true,
    isFeatured: true,
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "prod-5",
    name: "NEMA 17 Stepper Motor + DRV8825 Driver",
    slug: "nema-17-stepper-motor-drv8825",
    description: "Complete stepper motor kit featuring a NEMA 17 bipolar stepper motor and DRV8825 stepper motor driver with microstepping support up to 1/32 step.",
    shortDescription: "High-torque stepper motor with advanced driver board",
    price: 24.99,
    images: [
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=400&q=60",
    ],
    category: "Motors & Drivers",
    subCategory: "Stepper Motors",
    brand: "Q9 Labs",
    inStock: true,
    stockQuantity: 890,
    rating: 4.6,
    reviewCount: 632,
    specifications: {
      "Step Angle": "1.8°",
      "Motor Length": "48mm",
      "Rated Current": "1.5A/phase",
      "Torque": "0.45 Nm",
      "Driver Microsteps": "1, 1/2, 1/4, 1/8, 1/16, 1/32",
      "Driver Voltage": "8.2V - 45V",
      "Driver Current": "Up to 2.5A",
    },
    features: [
      "High torque density in compact form factor",
      "Smooth microstepping operation",
      "Over-temperature protection",
      "Cross-current protection",
      "Plug-and-play with most control boards",
    ],
    tags: ["stepper", "motor", "driver", "nema17", "cnc", "3d-printer"],
    isFeatured: true,
    createdAt: "2025-09-10T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "prod-6",
    name: "HC-SR04 Ultrasonic Distance Sensor",
    slug: "hc-sr04-ultrasonic-sensor",
    description: "The HC-SR04 ultrasonic sensor uses sonar to determine distance to an object like bats do. It offers excellent non-contact range detection with high accuracy and stable readings.",
    shortDescription: "Reliable ultrasonic ranging from 2cm to 400cm",
    price: 2.99,
    images: [
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=400&q=60",
    ],
    category: "Sensors & Modules",
    subCategory: "Motion & Distance",
    brand: "Q9 Labs",
    inStock: true,
    stockQuantity: 15000,
    rating: 4.4,
    reviewCount: 4521,
    specifications: {
      "Range": "2cm - 400cm",
      "Accuracy": "±3mm",
      "Operating Voltage": "5V DC",
      "Operating Current": "15mA",
      "Trigger Signal": "10µs TTL pulse",
      "Echo Signal": "TTL pulse proportional to range",
      "Frequency": "40kHz",
    },
    features: [
      "Contactless measurement",
      "Stable and reliable readings",
      "Compact and easy to mount",
      "Works with any microcontroller",
      "4-pin interface for easy wiring",
    ],
    tags: ["ultrasonic", "distance", "sensor", "hc-sr04"],
    isFeatured: true,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "prod-7",
    name: "128x64 OLED Display Module (I2C)",
    slug: "128x64-oled-display-i2c",
    description: "A compact 0.96-inch OLED display with 128x64 resolution, featuring I2C interface for easy integration with any microcontroller. Blue and white color options available.",
    shortDescription: "Compact 0.96-inch OLED with crisp I2C interface",
    price: 6.99,
    images: [
      "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&q=60",
    ],
    category: "Displays & OLEDs",
    subCategory: "OLED Displays",
    brand: "Q9 Labs",
    inStock: true,
    stockQuantity: 4500,
    rating: 4.7,
    reviewCount: 2341,
    specifications: {
      "Resolution": "128 x 64",
      "Diagonal": "0.96 inches",
      "Interface": "I2C (address 0x3C)",
      "Operating Voltage": "3.3V - 5V",
      "Color": "White / Blue",
      "Driver IC": "SSD1306",
      "View Angle": ">160°",
    },
    features: [
      "No backlight needed - OLED is self-illuminating",
      "Low power consumption",
      "Wide viewing angle",
      "I2C interface uses only 2 wires",
      "Multiple libraries available",
    ],
    tags: ["oled", "display", "i2c", "ssd1306", "128x64"],
    isFeatured: false,
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2026-01-05T00:00:00Z",
  },
  {
    id: "prod-8",
    name: "LM2596 DC-DC Buck Converter Module",
    slug: "lm2596-dc-dc-buck-converter",
    description: "Adjustable step-down voltage regulator module based on the LM2596 IC, capable of delivering up to 3A output current with high efficiency.",
    shortDescription: "Adjustable step-down regulator, 3A output",
    price: 3.49,
    images: [
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=400&q=60",
    ],
    category: "Power Management",
    subCategory: "DC-DC Converters",
    brand: "Texas Instruments",
    inStock: true,
    stockQuantity: 6700,
    rating: 4.5,
    reviewCount: 1823,
    specifications: {
      "Input Voltage": "4.5V - 40V",
      "Output Voltage": "1.25V - 37V (adjustable)",
      "Output Current": "3A (max)",
      "Efficiency": "Up to 92%",
      "Switching Frequency": "150kHz",
      "Protection": "Thermal shutdown, current limit",
    },
    features: [
      "High efficiency step-down conversion",
      "Adjustable output voltage via trimmer",
      "Thermal shutdown and over-current protection",
      "Low standby current",
      "Compact module design",
    ],
    tags: ["buck", "converter", "dc-dc", "lm2596", "voltage-regulator"],
    createdAt: "2025-05-15T00:00:00Z",
    updatedAt: "2025-11-20T00:00:00Z",
  },
  {
    id: "prod-9",
    name: "40-Pin Female-to-Female Jumper Wires (120mm)",
    slug: "40-pin-female-female-jumper-wires",
    description: "Premium quality female-to-female Dupont jumper wires in a 40-pin ribbon. Perfect for breadboard prototyping and connecting modules to microcontrollers.",
    shortDescription: "Premium Dupont jumper wire set, 40-pin ribbon",
    price: 2.49,
    images: [
      "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=400&q=60",
    ],
    category: "Connectors & Cables",
    subCategory: "Pin Headers",
    brand: "Q9 Labs",
    inStock: true,
    stockQuantity: 20000,
    rating: 4.3,
    reviewCount: 5123,
    specifications: {
      "Type": "Female to Female",
      "Pin Count": "40",
      "Length": "120mm",
      "Pitch": "2.54mm",
      "Wire Gauge": "26 AWG",
      "Connector": "Dupont",
      "Color": "Multicolor ribbon",
    },
    features: [
      "Color-coded for easy identification",
      "Reliable gold-plated connectors",
      "Flexible 26AWG wire",
      "Snap-apart ribbon design",
      "Compatible with standard breadboards",
    ],
    tags: ["jumper-wires", "dupont", "proto-type", "breadboard"],
    isOnSale: true,
    createdAt: "2025-04-01T00:00:00Z",
    updatedAt: "2025-10-15T00:00:00Z",
  },
  {
    id: "prod-10",
    name: "MPU6050 6-Axis Gyroscope + Accelerometer",
    slug: "mpu6050-6-axis-gyroscope-accelerometer",
    description: "The MPU6050 is the world's first integrated 6-axis motion tracking device that combines a 3-axis gyroscope and 3-axis accelerometer on a single silicon die.",
    shortDescription: "Integrated 6-axis motion tracking sensor module",
    price: 5.99,
    images: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=60",
    ],
    category: "Sensors & Modules",
    subCategory: "Motion & Distance",
    brand: "TDK InvenSense",
    inStock: true,
    stockQuantity: 3200,
    rating: 4.6,
    reviewCount: 2876,
    specifications: {
      "Gyro Range": "±250, ±500, ±1000, ±2000 °/s",
      "Accel Range": "±2g, ±4g, ±8g, ±16g",
      "Interface": "I2C (up to 400kHz)",
      "Operating Voltage": "3.3V - 5V",
      "Current": "3.6mA (full operation)",
      "DMP": "Built-in Digital Motion Processor",
    },
    features: [
      "3-axis gyroscope with programmable ranges",
      "3-axis accelerometer with programmable ranges",
      "Built-in Digital Motion Processor (DMP)",
      "6-axis MotionFusion data",
      "Low power sleep mode",
    ],
    tags: ["mpu6050", "gyroscope", "accelerometer", "imu", "motion"],
    isFeatured: true,
    createdAt: "2025-06-20T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "prod-11",
    name: "STM32F103C8T6 Blue Pill Board",
    slug: "stm32f103c8t6-blue-pill",
    description: "The STM32 Blue Pill is a compact development board based on the STM32F103C8T6 ARM Cortex-M3 microcontroller, offering powerful 32-bit performance at an affordable price.",
    shortDescription: "Compact ARM Cortex-M3 development board",
    price: 3.99,
    images: [
      "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=400&q=60",
    ],
    category: "Microcontrollers",
    subCategory: "STM32",
    brand: "STMicroelectronics",
    inStock: true,
    stockQuantity: 5600,
    rating: 4.4,
    reviewCount: 1456,
    specifications: {
      "MCU": "STM32F103C8T6 (ARM Cortex-M3)",
      "Clock Speed": "72 MHz",
      "SRAM": "20 KB",
      "Flash": "64 KB",
      "GPIO": "37",
      "ADC": "2x 12-bit, 10 channels",
      "Timers": "4x 16-bit",
      "Interfaces": "SPI, I2C, USART, CAN, USB",
    },
    features: [
      "Powerful 32-bit ARM Cortex-M3 core",
      "Rich peripheral set",
      "USB 2.0 interface",
      "SWD debug interface",
      "Arduino-compatible pin layout",
    ],
    tags: ["stm32", "blue-pill", "arm", "cortex-m3", "microcontroller"],
    isOnSale: true,
    createdAt: "2025-03-15T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "prod-12",
    name: "2.8-Inch TFT LCD Touch Shield",
    slug: "2-8-inch-tft-lcd-touch-shield",
    description: "A 2.8-inch TFT LCD display with resistive touch screen, designed as an Arduino shield for easy plug-and-play operation. Features 320x240 resolution and 65K colors.",
    shortDescription: "Color TFT display with resistive touch for Arduino",
    price: 18.99,
    originalPrice: 24.99,
    images: [
      "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&q=60",
    ],
    category: "Displays & OLEDs",
    subCategory: "TFT LCD",
    brand: "Q9 Labs",
    inStock: true,
    stockQuantity: 890,
    rating: 4.5,
    reviewCount: 672,
    specifications: {
      "Display Size": "2.8 inches",
      "Resolution": "320 x 240",
      "Color Depth": "65K (16-bit)",
      "Touch": "Resistive",
      "Interface": "8-bit parallel / SPI",
      "Driver IC": "ILI9341",
      "Operating Voltage": "5V / 3.3V",
    },
    features: [
      "Vibrant color display with 65K colors",
      "Resistive touch for user interaction",
      "SD card slot for media storage",
      "Plug-and-play Arduino shield design",
      "Includes touch pen and library",
    ],
    tags: ["tft", "lcd", "display", "touch", "arduino", "shield"],
    isOnSale: true,
    createdAt: "2025-08-10T00:00:00Z",
    updatedAt: "2026-01-25T00:00:00Z",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase()
  );
}

export function getRelatedProducts(product: Product): Product[] {
  return products
    .filter(
      (p) =>
        p.category === product.category &&
        p.id !== product.id
    )
    .slice(0, 4);
}
